### ISSUE TITLE
Alter CSS of "Jump to Bottom" button to avoid getting hidden by modules

### ISSUE THREAD

**Issue by morepurplemorebetter** [foundryvtt/foundryvtt#10005]
### User Experience

When a module adds something to the chat controls that increases the height of that area (e.g. [Dice Tray module](https://gitlab.com/asacolips-projects/foundry-mods/foundry-vtt-dice-calculator)), the "Jump to Bottom" button gets hidden behind the text input field, because the button is set to a fixed distance from the bottom. It could be made dynamic with a little change to the CSS.

Change the current rules in `style.css` from:
```css
.jump-to-bottom {
	background-color: rgba(0, 0, 0, 0.5);
	position: absolute;
	bottom: 134px;
	padding: 5px;
	width: 300px;
}
.jump-to-bottom > a {
	text-align: center;
}
```

to:
```css
.jump-to-bottom {} /* no longer needed */
.jump-to-bottom.flexrow { /* requires more specific selector to overrule other CSS rules */
	flex-grow: 0;
}
.jump-to-bottom > a {
	text-align: center;
	position: absolute;
	bottom: 0;
	background-color: rgba(0, 0, 0, 0.5);
	padding: 5px;
	width: 300px;
}
```

### The current state
![image](https://github.com/foundryvtt/foundryvtt/assets/8971168/9f7738b0-6f87-401e-b5ec-6a21dff16388)
> Screenshot from FoundryVTT 11.308 with Dice Tray v1.5.3 with an added `z-index: 999;` to the `.jump-to-bottom ` the element so it isn't lying below the chat box.

### With my proposed changes
![image](https://github.com/foundryvtt/foundryvtt/assets/8971168/29f0dc69-0c20-4916-9677-55130819c9d2)
> Screenshot, same as above, with my proposed CSS changes active.
