### ISSUE TITLE
Make Folders Sticky

### ISSUE THREAD

**Issue by kristianserrano** [foundryvtt/foundryvtt#10263]
### User Experience

In an attempt to help with viewing nested folders, I wrote a small bit of CSS to make folders sticky. I think it vastly improves the experience of sifting through folders in the sidebar.
I added the following CSS to `li.folder > .folder-header`:
```css
li.folder > .folder-header {
    ...
    position: sticky;
    top: 0;
    z-index: 2; /* This doesn't have to be specifically 2 */
}
```

Here's the result:

https://github.com/foundryvtt/foundryvtt/assets/1796189/77026068-7390-4641-ba60-ddd8da210269

**Comment by kristianserrano** [comment]
It looks like there are some inline styles being added to folders in other directories that set their position to `relative`, and this would require the default folder `background-color` to be opaque (added above).

**Comment by aaclayton** [comment]
I agree that's pretty nice. Good suggestion @kristianserrano.

**Comment by kristianserrano** [comment]
Sweet! I found there are a few additional style tweaks (opacity on subfolders), but I'm sure you all will solve them pretty easily when you get into it. Looking forward to seeing it in core!

**Comment by kristianserrano** [comment]
Here's a demo of it working with subfolders as well.

https://github.com/foundryvtt/foundryvtt/assets/1796189/88557351-6a72-4a37-99fe-6a3274712e1a

**Comment by aaclayton** [comment]
High priority to evaluate this, but probably not for V12 dev 2. We can do this during the user testing phase.

**Comment by kristianserrano** [comment]
@Fyorl here are the _overrides_ I applied to achieve the sticky folder headers (using CSS nesting, but this can be flattened of course).
```css
.folder > .folder-header {
    --folder-header-height: 38px;
    position: sticky !important;
    top: 0;
    background: rgba(0, 0, 0);
    z-index: calc(var(--z-index-app) + 3);

    & + .subdirectory > .folder > .folder-header {
        top: var(--folder-header-height);
        z-index: calc(var(--z-index-app) + 2);
        
        & + .subdirectory > .folder > .folder-header {
            top: calc(var(--folder-header-height) * 2);
            z-index: calc(var(--z-index-app) + 1);
        }
    }
}
```
This works pretty well visually. The only limitation I ran into was the stacking context of the context menu. Because it's inserted as a child of its respective folder header, it's z-index context is relative to that parent. Thus, subfolders with a higher z-index are rendered over it.

One possible solution might be to remove the use of z-indexing to have sibling list item folder headers cover their previous siblings and instead use the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) to remove/override `position: sticky` on a previous sibling's folder header so that it scrolls on when the current one hits its `top` position. I haven't attempted this yet myself.

**Comment by kristianserrano** [comment]
I found a hacky way of achieving this with the current method of injecting the context menu. I hacked it together with some CSS overrides and a tiny bit of JS that applies an inline z-index to all folders and folder-headers. It might be possible to insert the z-index in the Handlebars template instead.

If you're curious...
```css
.directory-list {
    --context-menu-z-index: 10000000;
    --folder-header-height: 38px;

    & .folder-header {
        position: sticky !important;

        & > #context-menu {
            top: calc(100% + 1px);
            z-index: var(--context-menu-z-index);
        }
    }

    & .directory-item header > #context-menu {
        z-index: var(--context-menu-z-index);
    }

    & > .folder > .folder-header {
        top: 0;

        & + .subdirectory > .folder > .folder-header {
            top: var(--folder-header-height);

            & + .subdirectory > .folder  > .folder-header {
                top: calc(var(--folder-header-height) * 2);
            }
        }
    }
}
```

```js
// Loop through the folders and folder headers to assign a decrementing z-index value. This sets the first folder sibling's header to have a higher z-index than the next.
const list = document.querySelectorAll('.directory-list .folder');
let int = 10000000;
for (const item of list){
    int -= 1;
    item.style.zIndex = int;
    item.querySelector('.folder-header').style.zIndex = int;
}
```
