### ISSUE TITLE
Some CSS Styles are throwing errors with Prosemirror

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#10279]
### What happened?

Reported here: https://discord.com/channels/170995199584108546/1065764070680186930/1179345341091430430

I have a css style for tables which i add with classes to my journals.
The css rule is:

```css
.ah5e-journal tbody.av5e {
    font-size: 0.9rem;
}

.ah5e-journal tbody.av5e tr:first-child {
    background-color: #008B8B;
    color: white;
    font-weight: bold;
}
```
If i use the tinymce editor, i can add the class without problems. But in the prosemirror, i geht the error in the screenshot.

![image](https://github.com/foundryvtt/foundryvtt/assets/66535080/7d159b0a-9b7a-4b74-8625-b8fed9ddeef1)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

I dont know how to describe this. Sorry.

### What core version are you reporting this for?

Versi

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled
