### ISSUE TITLE
When there are more than eight combat encounters, the "encounter counter" at the top of the combat tracker is the wrong color

### ISSUE THREAD

**Issue by n3dst4** [foundryvtt/foundryvtt#12872]
### What happened?

If the GM creates more than eight combat encounters, the top bar of the combat tracker switches from showing one button per encounter ( [1] [2] [3] etc), to a count and total with forwards/backwards buttons (e.g. ◀ 7/9 ▶).

When the UI is in "light mode", the combat counter is using the text color from dark mode, so it's barely legible against the light background.

### What ways of accessing Foundry can you encounter this issue in?

- [x] Native App (Electron)
- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Other

### Reproduction Steps

1. Load a world with any system that doesn't replace the combat tracker (I used 5e because why not.)
2. In core settings  -> Configure Interface, set the "Interface" mode to "Light".
3. **Create nine combat encounters** by clicking the ➕ button in the combat sidebar nine times.
4. Note on the ninth one that the tracker switches from showing buttons to showing numbers with next/previous controls.

Expected: the text should be using the same color as the rest of the sidebar UI.

Actual: It's using the text color from the dark theme and is barely legible.

## Screenshots

Dark mode (works fine):

![Image](https://github.com/user-attachments/assets/7a8ae7f5-e06b-4afe-aa1c-48bd89c81d58)

Light mode:

![Image](https://github.com/user-attachments/assets/c6d0da96-1f8c-4ee0-9e7f-4f2b542cfe9a)

## Notes

For the encounter title, there's some CSS:

```css
.combat-sidebar .combat-tracker-header .encounter-controls .encounter-title {
  /* ... other bits... */
  color: var(--color-text-secondary);
}
```

Looks like we also need:

```css
.combat-sidebar .combat-tracker-header .encounters .encounter-count {
    color: var(--color-text-secondary);
}
```

### What core version are you reporting this for?

v13 342

### Relevant log output

```shell

```

### Bug Checklist

- [x] The issue occurs while all Modules are disabled
