### ISSUE TITLE
Add styling to disabled range inputs

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6085]
Originally in GitLab by @stwlam

### Feature Summary

A disabled range input does not indicate its disabledness until one tries to move the slider "thumb." It would be convenient were it to have special styling so as to inform the user. We just added some for the pf2e system, which may or may not be a good example to follow (design is our ...):

```scss
// Disabled range input
input[type="range"]:disabled {
    &::-webkit-slider-runnable-track {
        background: #cac9c7;
        border: none;
        box-shadow: 0 0 1px #cac9c7;
        cursor: default;
    }
    &::-moz-range-track {
        background: #cac9c7;
        border: none;
        box-shadow: 0 0 1px #cac9c7;
        cursor: default;
    }
    &::-webkit-slider-thumb {
        background: white;
        border: none;
        box-shadow: 0 0 1px #cac9c7;
        cursor: default;
    }
    &::-moz-range-thumb {
        background: white;
        border: none;
        box-shadow: 0 0 1px #cac9c7;
        cursor: default;
    }
}
```

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/01e34a5d65d40936670e94284f7642d6/Screenshot_from_2021-11-09_14-23-27.png)

### User Experience

The user sees a range input and can immediately make out that it is disabled.

### Priority/Importance

Add to the pile of sundry minor issues?
