### ISSUE TITLE
Using an image in the journal and giving it a width distorts the image

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#8231]
From https://discord.com/channels/170995199584108546/956306859491471420/1021200994677293056

Using an image in the journal and giving it a width distorts the image on the journal sheet as the style.css has a max-height declaration which of course runs into issues with me setting up a width for the image. 

```css
.sheet.journal-entry article img:not(.nopopout) {
    cursor: pointer;
    max-height: 680px;
}
```

Video: https://cdn.discordapp.com/attachments/956306859491471420/1021200994450817154/embedded_image_display_issue.mp4
