### ISSUE TITLE
Banner images are not centered vertically

### ISSUE THREAD

**Issue by kristianserrano** [foundryvtt/foundryvtt#9445]
### What happened?

In V11, banner images for packs are vertically aligned to the top of the image.

The following CSS change should do the trick
```css
.compendium-sidebar .directory-item.compendium .compendium-banner {
  object-position: center;
}
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Look at a taller banner images.

### What core version are you reporting this for?

Version 11 Testing 3

### Bug Checklist

- [X] The issue occurs while all Modules are disabled
