### ISSUE TITLE
Enlarge the default ActiveEffect sheet slightly to better accommodate the ProseMirror editor

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt#9484]
### User Experience

The editor doesn't have enough space both vertically and horizontally. In addition, the editor's save button closes the sheet and has no 'display mode'.

![image](https://github.com/foundryvtt/foundryvtt/assets/50169243/c131b4ee-abe5-489d-a7ff-badba1dffb1f)

Some quick css that makes it look better:

```css
.active-effect-sheet .editor {
    height: 250px;
}

.active-effect-sheet {
    min-width: 600px;
}
```

![image](https://github.com/foundryvtt/foundryvtt/assets/50169243/411bd150-d744-4e2f-b1db-1883d87fb278)
