### ISSUE TITLE
Allow collapsing the Players List

### ISSUE THREAD

**Issue by jjspace** [foundryvtt/foundryvtt#9918]
### User Experience

It would be really nice to collapse the Party list after a session has started.

I play on a slightly smaller window size and like to collapse and hide as much of the UI as possible to focus on the tokens and map of the game. I don't find the player list useful and would prefer to hide it. I assumed the arrow at the top would let me do that but I realized that only makes it _bigger_ to show offline players instead of hiding it completely.

I achieved an effect similar to what I want by adding these styles to the page but I think it'd be a good addition for everyone to have that ability.

```css
#players {
  height: 40px;
  overflow: hidden;
}

#players:hover {
  height: unset;
  overflow: unset;
}
```

![2023-08-12_12-48-13](https://github.com/foundryvtt/foundryvtt/assets/8007967/fae428af-65df-4f36-b952-86375634aa81)
